[
    {
        title: "iPhone 17 Pro Max - 256GB",
        shortDescription:
            "Experience the future with A18 Bionic chip, 48MP camera system, and all-day battery life.",
        description:
            "The iPhone 17 Pro Max pushes the boundaries of what's possible. Featuring the revolutionary A18 Bionic chip with next-gen neural engine, a stunning 6.9-inch Super Retina XDR display with ProMotion and always-on technology. The advanced pro camera system with 48MP main sensor, 12MP ultra-wide, and 12MP telephoto with 5x optical zoom captures studio-quality photos and videos. Titanium design with Ceramic Shield front, making it incredibly durable. iOS 18 brings new levels of customization and intelligence to your iPhone.",
        highlights: [
            "A18 Bionic chip with 6-core CPU and 6-core GPU",
            "6.9-inch Super Retina XDR display with Always-On",
            "Pro camera system: 48MP Main | 12MP Ultra Wide | 12MP Telephoto (5x optical zoom)",
            "Up to 33 hours video playback",
            "Titanium design with Ceramic Shield",
            "Face ID with enhanced security",
            "5G capable | Wi-Fi 7 | Bluetooth 5.4",
            "USB-C with USB 3.0 support",
        ],
        vendor: "65f8a3b2c4d5e6f7a8b9c0d1", //
        brand: "65f8a3b2c4d5e6f7a8b9c0d2",
        brandName: "Apple",
        category: "65f8a3b2c4d5e6f7a8b9c0d3",
        subCategory: "65f8a3b2c4d5e6f7a8b9c0d4",
        tags: ["iphone", "apple", "smartphone", "5g", "pro max", "flagship", "ios"],
        collections: ["65f8a3b2c4d5e6f7a8b9c0d5", "65f8a3b2c4d5e6f7a8b9c0d6"],
        price: {
            amount: 159900,
            currency: "BDT",
        },
        compareAtPrice: {
            amount: 169900,
            currency: "BDT",
        },
        discount: {
            type: "percentage",
            value: 5.88,
            effectivePrice: 150500,
            startDate: "2025-01-15T00:00:00Z",
            endDate: "2025-02-15T23:59:59Z",
        },
        taxRate: 15,
        isTaxable: true,
        sku: "IP17PM-256-SPACE-BLK",
        stock: 50,
        reservedStock: 5,
        lowStockThreshold: 10,
        backorderAllowed: true,
        maxOrderQuantity: 10,
        minOrderQuantity: 1,
        thumbnail: {
            url: "https://res.cloudinary.com/zuzuva/image/upload/v1234567890/products/iphone17promax/thumbnail.jpg",
            filename: "iphone17promax-thumbnail.jpg",
            originalName: "iphone17-pro-max-space-black.jpg",
            alt: "iPhone 17 Pro Max Space Black - Front and Back View",
            width: 800,
            height: 800,
            size: 245000,
            mimetype: "image/jpeg",
        },
        images: [
            {
                url: "https://res.cloudinary.com/zuzuva/image/upload/v1234567890/products/iphone17promax/img1.jpg",
                filename: "iphone17promax-img1.jpg",
                originalName: "iphone17-front-view.jpg",
                alt: "iPhone 17 Pro Max front display",
                size: 320000,
                mimetype: "image/jpeg",
                width: 2000,
                height: 2000,
                sortOrder: 0,
            },
            {
                url: "https://res.cloudinary.com/zuzuva/image/upload/v1234567890/products/iphone17promax/img2.jpg",
                filename: "iphone17promax-img2.jpg",
                originalName: "iphone17-back-cameras.jpg",
                alt: "iPhone 17 Pro Max triple camera system",
                size: 380000,
                mimetype: "image/jpeg",
                width: 2000,
                height: 2000,
                sortOrder: 1,
            },
            {
                url: "https://res.cloudinary.com/zuzuva/image/upload/v1234567890/products/iphone17promax/img3.jpg",
                filename: "iphone17promax-img3.jpg",
                originalName: "iphone17-side-titanium.jpg",
                alt: "iPhone 17 Pro Max titanium edge",
                size: 298000,
                mimetype: "image/jpeg",
                width: 2000,
                height: 2000,
                sortOrder: 2,
            },
        ],
        videos: [
            {
                url: "https://res.cloudinary.com/zuzuva/video/upload/v1234567890/products/iphone17promax/promo.mp4",
                filename: "iphone17-promo.mp4",
                title: "iPhone 17 Pro Max Official Promo",
                duration: 180,
                sortOrder: 0,
            },
        ],
        hasVariants: true,
        variantOptions: [
            {
                name: "Color",
                values: ["Space Black", "Titanium Silver", "Deep Purple", "Forest Green"],
                displayType: "swatch",
                isRequired: true,
            },
            {
                name: "Storage",
                values: ["256GB", "512GB", "1TB"],
                displayType: "button",
                isRequired: true,
            },
        ],
        variants: [
            {
                combination: [
                    { name: "Color", value: "Space Black" },
                    { name: "Storage", value: "256GB" },
                ],
                sku: "IP17PM-256-BLK",
                barcode: "8901234567890",
                price: { amount: 159900, currency: "BDT" },
                compareAtPrice: { amount: 169900, currency: "BDT" },
                discount: {
                    type: "percentage",
                    value: 5.88,
                    effectivePrice: 150500,
                },
                stock: 25,
                reservedStock: 3,
                images: [],
                weight: 0.221,
                dimensions: {
                    length: 16.08,
                    width: 7.81,
                    height: 0.85,
                },
                isActive: true,
                sortOrder: 0,
            },
            {
                combination: [
                    { name: "Color", value: "Deep Purple" },
                    { name: "Storage", value: "512GB" },
                ],
                sku: "IP17PM-512-PRP",
                barcode: "8901234567891",
                price: { amount: 179900, currency: "BDT" },
                compareAtPrice: { amount: 189900, currency: "BDT" },
                discount: {
                    type: "percentage",
                    value: 5.26,
                    effectivePrice: 170500,
                },
                stock: 15,
                reservedStock: 2,
                images: [],
                weight: 0.221,
                dimensions: {
                    length: 16.08,
                    width: 7.81,
                    height: 0.85,
                },
                isActive: true,
                sortOrder: 1,
            },
            {
                combination: [
                    { name: "Color", value: "Titanium Silver" },
                    { name: "Storage", value: "256GB" },
                ],
                sku: "IP17PM-256-SIL",
                barcode: "8901234567892",
                price: { amount: 159900, currency: "BDT" },
                compareAtPrice: { amount: 169900, currency: "BDT" },
                discount: {
                    type: "percentage",
                    value: 5.88,
                    effectivePrice: 150500,
                },
                stock: 10,
                reservedStock: 0,
                images: [],
                weight: 0.221,
                dimensions: {
                    length: 16.08,
                    width: 7.81,
                    height: 0.85,
                },
                isActive: true,
                sortOrder: 2,
            },
        ],
        attributes: [
            {
                groupName: "Display",
                key: "Screen Size",
                value: "6.9 inch",
                unit: "inch",
                isFilterable: true,
                isVisible: true,
            },
            {
                groupName: "Display",
                key: "Resolution",
                value: "2796 x 1290",
                unit: "pixels",
                isFilterable: false,
                isVisible: true,
            },
            {
                groupName: "Display",
                key: "Refresh Rate",
                value: "120",
                unit: "Hz",
                isFilterable: true,
                isVisible: true,
            },
            {
                groupName: "Processor",
                key: "Chip",
                value: "A18 Bionic",
                unit: "",
                isFilterable: true,
                isVisible: true,
            },
            {
                groupName: "Processor",
                key: "RAM",
                value: "12",
                unit: "GB",
                isFilterable: true,
                isVisible: true,
            },
            {
                groupName: "Camera",
                key: "Main Camera",
                value: "48",
                unit: "MP",
                isFilterable: true,
                isVisible: true,
            },
            {
                groupName: "Camera",
                key: "Optical Zoom",
                value: "5x",
                unit: "",
                isFilterable: true,
                isVisible: true,
            },
            {
                groupName: "Battery",
                key: "Video Playback",
                value: "33",
                unit: "hours",
                isFilterable: false,
                isVisible: true,
            },
            {
                groupName: "Connectivity",
                key: "5G",
                value: "Yes",
                unit: "",
                isFilterable: true,
                isVisible: true,
            },
            {
                groupName: "Connectivity",
                key: "Wi-Fi",
                value: "Wi-Fi 7",
                unit: "",
                isFilterable: true,
                isVisible: true,
            },
        ],
        delivery: {
            weight: 0.35,
            dimensions: {
                length: 19.5,
                width: 10.5,
                height: 6.5,
            },
            shippingClass: "express",
            isFreeShipping: false,
            estimatedDelivery: "2-3 business days",
            handlingTime: 2,
        },
        returnPolicy:
            "30-day return policy. Item must be unopened with original seal. Return shipping fee applies.",
        warrantyInfo:
            "1 year Apple warranty through authorized service centers. Additional 6 months on battery.",
        countryOfOrigin: "China",
        seo: {
            slug: "iphone-17-pro-max-256gb-space-black",
            metaTitle: "iPhone 17 Pro Max 256GB - A18 Bionic Chip | Zuzuva",
            metaDescription:
                "Buy iPhone 17 Pro Max with A18 Bionic chip, 48MP camera, titanium design. Free shipping on premium smartphones in Bangladesh.",
            canonicalUrl: "https://zuzuva.com/product/iphone-17-pro-max-256gb",
            keywords: [
                "iPhone 17",
                "iPhone 17 Pro Max",
                "Apple smartphone",
                "best mobile phone 2025",
                "premium smartphone Bangladesh",
            ],
            schema: {
                "@context": "https://schema.org",
                "@type": "Product",
                name: "iPhone 17 Pro Max 256GB",
                brand: "Apple",
                sku: "IP17PM-256-SPACE-BLK",
            },
        },
        visibility: "visible",
        status: "published",
        isActive: true,
        isFeatured: true,
        isDeleted: false,
        publishedAt: "2025-01-10T10:00:00Z",
        availableFrom: "2025-01-15T00:00:00Z",
        availableTo: "2026-12-31T23:59:59Z",
        createdBy: "65f8a3b2c4d5e6f7a8b9c0d1",
        creatorModel: "Seller",
        approvedBy: "65f8a3b2c4d5e6f7a8b9c0d7",
        approvedAt: "2025-01-09T14:30:00Z",
        lastModifiedBy: "65f8a3b2c4d5e6f7a8b9c0d1",
        lastModifiedByModel: "Seller",
        metadata: {
            color: "#1A1A1A",
            releaseYear: 2025,
            waterResistant: "IP68",
            chargingSpeed: "45W wired",
            wirelessCharging: "25W MagSafe",
        },
    },
];
